### ISSUE TITLE
Devs are incomplete

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/bowler-proto#3]
We need a way to specify the contents of the local files for a dev. Right now, we can specify that a project is dev'd, but we have no way to specify the local changes inside that dev.

**Comment by nickmertin** [comment]
This is incorrect. The specification of a dev'd dependency is a `bowler.gif_f_s.ProjectSpec`, which includes a commit ID and local changes patch (the same form as that of the current project).

**Comment by Octogonapus** [comment]
Oh, right. I missed that somehow.
