### ISSUE TITLE
Support task cancellation

### ISSUE THREAD

**Issue by Octogonapus** [CommonWealthRobotics/bowler-proto#4]
We need a way for the client to tell the kernel to cancel a task. Something like:
```
message CancelTaskRequest {
    int64 task_id = 1;
}
```

**Comment by nickmertin** [comment]
Do you think it would be appropriate to add a field of some sort to `TaskEnd` to indicate how the task ended (cancelled, failed, succeeded)? Possibly also an optional error description?

**Comment by Octogonapus** [comment]
> Do you think it would be appropriate to add a field of some sort to TaskEnd to indicate how the task ended (cancelled, failed, succeeded)? Possibly also an optional error description?

Yes, both of those things sound appropriate.
